### ISSUE TITLE
Colors & Fonts setting for Folded text gets modified when using plugin

### ISSUE THREAD

**Issue by nathanmbrown** [cheptsov/AdvancedExpressionFolding#46]
I don't know if this is an issue in IDEA, or is caused by the plugin, but this is what happens.
Without the plugin installed the Folded text formatting can be set up ok and persists fine:
![image](https://cloud.githubusercontent.com/assets/1790828/25277690/aaded874-2697-11e7-9f73-c8c49fb8479f.png)
However, installing the plugin, and opening a file with folding active, the folded code isn't shown bold, and if I then open the settings I see that the bold formatting has been turned off:
![image](https://cloud.githubusercontent.com/assets/1790828/25277584/3ce74478-2697-11e7-9c71-18cc59322ba7.png)
If I reset the bold on, it will be turned off again if I switch to a different file.
This has only started happening in the last few versions of the plugin. When the problem first started it was losing the Foreground colour, but that changed in a more recent plugin version to the Bold.
I'm using IDEA 2017.1.2 EAP, although this happened with 2017.1.1 too iirc.

**Comment by ciscorucinski** [comment]
I had similar effects before. See `Other Side Effects` in #40 After I updated the plugin, I no longer had that issue at all.

But, I had a dark custom color scheme, and the plugin changed the foreground and background color to be white and grey. This only seemed to effect custom color schemes, though. The built-in color schemes were not effected at all.

**Comment by NaomiRP** [comment]
I am running into this with plugin version 0.9.6 and IntelliJ IDEA 2017.2, both while using the Darcula scheme with a few customizations and while using a copy of the Darcula scheme with the same modifications.

I customize folded text to be italicized and add a light blue foreground color.  Intermittently (sometimes when opening a new file, sometimes when expanding a folded section, sometimes when making changes to an already open file outside of any folded areas), the light blue color and italicization disappear.  When I open preferences, the folded text colors setting has reverted again.  I can reset it to my preferred customization, but that takes at least 6 clicks which is annoying when the persistence of the setting is highly unreliable.

Additional environment details:
Build #IU-172.3317.76, built on July 15, 2017
JRE: 1.8.0_152-release-915-b5 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6 (I saw the same behavior on Mac OS X 10.12.5 too)

**Comment by NaomiRP** [comment]
I believe this issue is caused by [lines 104-108](https://github.com/cheptsov/AdvancedExpressionFolding/blob/fbab92893a08fd76d2e1c1de2a761e67cd6085dd/src/com/intellij/advancedExpressionFolding/AdvancedExpressionFoldingHighlightingComponent.java#L104-L108) of `AdvancedExpressionFoldingHighlightingComponent.java`:

``` java
                        TextAttributes foldedTextAttributes = editorEx.getColorsScheme().getAttributes(EditorColors.FOLDED_TEXT_ATTRIBUTES);
                        if (foldedTextAttributes.getBackgroundColor() != null) {
                            foldedTextAttributes.setForegroundColor(null);
                        }
                        foldedTextAttributes.setFontType(Font.PLAIN);
```

I tried updating my custom folded attributes to light blue foreground color, italicized, and no background color.  (I usually keep the Darcula default #3A3A3A folded text background color.)   As this code suggests, the light blue foreground color persisted when I opened a new file, but the italicization was cleared.  (I also noticed that if the file I opened had no advanced folding, my editor's folded text display settings were unchanged.)

**Comment by nathanmbrown** [comment]
This is still happening in 2017.3 EAP. It is without question due to the plugin, as everything was fine until I enabled it again to try it, then all folded areas lost their bold, even those that the plugin did not fold itself.

**Comment by NaomiRP** [comment]
In the current version of this code (master, commit [b826a91](https://github.com/cheptsov/AdvancedExpressionFolding/commit/b826a9121cb123969ceb57f9be63da7d952b6c18)), the problematic code has moved to a private method in lines 134-142.  On the latest version of IntelliJ (2017.3.4) and the plugin (0.9.9.8), this is still happening.  I have realized that Effects (such as a contrasting border) are not affected, so that may be a workaround to more easily identify folded text until this bug is fixed.
